---
title: "analise_ucsc_ucec.Rmd"
output: html_document
date: "2024-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

---
title: "Análise UCS e UCEC com maftools"
author: "VinSouzaa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(maftools)

# Dados clínicos
dados <- read.table("C:\\Users\\cicer\\Downloads\\nationwidechildrens.org_clinical_patient_ucs.txt", 
                    header = TRUE, sep = "\t")

# Arquivos MAF
maf_UCS <- read.maf(maf = "C:\\Users\\cicer\\Downloads\\a3a40aae-6b8e-4bf5-9fe1-4055f207a38a.wxs.aliquot_ensemble_masked.maf")
maf_UCEC <- read.maf(maf = "C:\\Users\\cicer\\Downloads\\d7433af4-2fd5-4a8e-84af-a1c86a73f4c6.wxs.aliquot_ensemble_masked.maf")
```

```{r setup, include=FALSE}
head(dados)
summary(dados)

# Listando os identificadores dos pacientes
list(dados$bcr_patient_uuid)
```

```{r setup, include=FALSE}
# Resumo de genes mutados no UCS
summary_UCS <- getGeneSummary(maf_UCS)
head(summary_UCS)
tail(summary_UCS)

# Resumo de genes mutados no UCEC
summary_UCEC <- getGeneSummary(maf_UCEC)
head(summary_UCEC)

# Tabelas adicionais
summary_UCS
summary_UCEC

# Frequência de amostras mutadas
table(summary_UCEC$MutatedSamples)

# Dados clínicos do UCEC
maf_UCEC@clinical.data$Tumor_Sample_Barcode
```

```{r setup, include=FALSE}
getSampleSummary(maf_UCS)
getGeneSummary(maf_UCS)
getClinicalData(maf_UCS)
getFields(maf_UCS) # Todos os campos disponíveis no MAF
```

```{r setup, include=FALSE}
# Fusão de UCS e UCEC
comp <- merge_mafs(mafs = c(maf_UCS, maf_UCEC))

# Resumo visual das cohortes
plotmafSummary(maf = maf_UCS, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
plotmafSummary(maf = maf_UCEC, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```

```{r setup, include=FALSE}
# Gráficos de barras
mafbarplot(maf_UCS)
mafbarplot(maf_UCEC)

# Oncoplots
oncoplot(maf_UCS, top = 10)
oncoplot(maf_UCEC, top = 10)

# Lollipop plots
lollipopPlot(maf_UCS, gene = 'TP53', AACol = 'HGVSp_Short', showMutationRate = TRUE)
lollipopPlot(maf_UCEC, gene = 'TP53', AACol = 'HGVSp_Short', showMutationRate = TRUE)

# Proteínas
plotProtein('TP53')

# Rainfall plot
rainfallPlot(maf_UCS)
```

```{r setup, include=FALSE}
# Comparação com TCGA
tcgaCompare(maf_UCEC)

# Frequência de alelos variantes
plotVaf(maf_UCS)

# Interações somáticas
somaticInteractions(comp, top = 25, pvalue = c(0.05, 0.1))

# Sobrevida
mafSurvival(maf_UCS, gene = 'TP53', time = 'days_to_last_followup', Status = 'Overall_Survival_Status', isTCGA = TRUE)

# Comparação de cohorts
mafCompare(maf_UCEC, maf_UCEC, minMut = 5)
forestPlot(comp, pVal = 0.1)
```



